# Generated by Django 4.2.11 on 2024-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_advanced_form_builder", "0003_auto_20230706_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailformfield",
            name="min_length",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="formfield",
            name="min_length",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
