# Generated by Django 4.2.11 on 2024-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_advanced_form_builder",
            "0004_emailformfield_min_length_formfield_min_length",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="emailformfield",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="emailformfield",
            name="toggled_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="formfield",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="formfield",
            name="toggled_label",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
